### ISSUE TITLE
Why is libselinux a dependency for this role?

### ISSUE THREAD

**Issue by jeffwidman** [Open-Future-Belgium/PostgreSQL#14]
https://github.com/Open-Future-Belgium/PostgreSQL/blob/master/tasks/RedHat.yml#L3

Why is libselinux required for installing/managing postgres? 

I don't see it listed as a dependency anywhere in the ansible postgres modules docs nor do I see it referenced elsewhere in this role.

**Comment by Trikke76** [comment]
you are right 
probably some leftover 
i will remove it
