### ISSUE TITLE
postgresql_env

### ISSUE THREAD

**Issue by kostyrevaa** [Open-Future-Belgium/PostgreSQL#31]
In defaults there's
```
postgresql_env:
  LC_ALL: "{{ postgresql_locale }}"
  LC_LCTYPE: "{{ postgresql_locale }}"
```
what is it for?
I've failed to find any mentions of it elsewhere in role.

**Comment by Trikke76** [comment]
I have removed the vars
those where localizations params i added but never got time to implement them into the role

maybe something we can add later if needed
