### ISSUE TITLE
with every ansible run postgresql restarts

### ISSUE THREAD

**Issue by kostyrevaa** [Open-Future-Belgium/PostgreSQL#37]
Are those
```
# {{ ansible_managed }}
```
really necessary ?
They cause PostgreSQL restarts every time.

**Comment by Trikke76** [comment]
what do you mean postgres restarts everytime ?
{{ ansible_managed }} is not realy necessary but it's nice to have 
this way it's clear what config is managed by ansible just in case people try to alter it.

**Comment by kostyrevaa** [comment]
I have master playbook with all hosts and theirs roles. Everytime I run ansible-playbook with this master plbk ansible changes postgres configs because that {{ ansible_manage }} always puts current date and time in configs.

**Comment by Trikke76** [comment]
why not alter your ansible.cfg and remove the date/time stamp ?
i suppose this would solve the problem 

we could remove the {{ ansible_managed }} from the templates if that is not resolving the issue 
but i prefer to keep it as a warning in environments where some sysadmins still try to alter manual settings.

**Comment by kostyrevaa** [comment]
So now you are forcing users to change something in cfg.
I'll give it a try

**Comment by Trikke76** [comment]
i'm not forcing anyone to change something in the ansible.cfg
you are not happy with ansible adding timestamps so remove it if you don't like the default ansible behaviour. 

{{ ansible_managed }} was made to warn users that cfg files are managed by ansible, removing it is an option but people might change the files by hand and be unaware of the automated changes later.

as far as i know there is no option to exclude date/time from {{ ansible_managed }} besides removing it from the ansible.cfg file

The only other option i see is to put a static comment in the file

**Comment by kostyrevaa** [comment]
OK, I changed ansible_managed in cfg
thank for tip!
