### ISSUE TITLE
please push tag

### ISSUE THREAD

**Issue by kostyrevaa** [Open-Future-Belgium/PostgreSQL#49]
Hello!
I'm using requirements.yml to install roles and it would be great if your role could be referenced with branch or tag. Thus one can be sure that backward-incompatible changes in master won't affect users.

**Comment by Trikke76** [comment]
i have added a new branch ansible1 we will use the master branch for ansible2 
no one gave feedback about moving to ansible 2 or stick with 1 so i have upgraded my ansible server last week to 2
