### ISSUE TITLE
No longer compatible with ansible 1.9.X

### ISSUE THREAD

**Issue by grokcode** [Open-Future-Belgium/PostgreSQL#52]
I recently started getting `ERROR: block is not a legal parameter in an Ansible task or handler`. It looks like a [recent commit](https://github.com/Open-Future-Belgium/PostgreSQL/commit/6be92db75637f64986948c05cfc4155e12126ed5) added the `block` parameter which only works with ansible 2.0. I'm just checking to see if this was a conscious change to drop support for earlier ansible versions, and if so, to request that the docs be updated to say that. Thanks!

**Comment by Trikke76** [comment]
Hi,

yes this was intentionally we had a discussion about this a while ago 
there is another branch ansible1 without the added code for 2.0

you are right i will update the docs next commit

**Comment by grokcode** [comment]
Thanks @Trikke76!
